### Endpoint de teste
GET http://localhost:3003/ping

### 1) Criar usuário
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Balsemao",
    "email": "balsemao@gmail.com",
    "password": "123abc"
}

### 2) Login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "balsemao@gmail.com",
    "password": "123abc"
}

### 3) Criar post
POST http://localhost:3003/posts
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYwZThmNzZiLTc3YjItNGY5Yy04YzJjLTgxMmFkODRiYzA1ZSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjM5NjMxMDEsImV4cCI6MTY2NDA0OTUwMX0.5AO-HfxGVuvQZ-CRui_7UVYj5qLkYAH5b9jRLdboR-8
Content-Type: application/json

{
    "content": "Olá mundo!"
}

### 4) Pegar todos os posts 
GET http://localhost:3003/posts
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYwZThmNzZiLTc3YjItNGY5Yy04YzJjLTgxMmFkODRiYzA1ZSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjM5NjMxMDEsImV4cCI6MTY2NDA0OTUwMX0.5AO-HfxGVuvQZ-CRui_7UVYj5qLkYAH5b9jRLdboR-8

### 5) Deletar post
DELETE http://localhost:3003/posts/92bc1f42-ce2c-4329-8420-72a368034320
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MDM5Mzk2MSwiZXhwIjoxNjYwNDgwMzYxfQ.FwOtXHKx1XXFnMot-CJstZPCzEORAtPrwd3iz8QAg5A

### 6) Like post
POST http://localhost:3003/posts/like/a589f9f1-a430-4d75-84bb-c2c856864f87
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYwZThmNzZiLTc3YjItNGY5Yy04YzJjLTgxMmFkODRiYzA1ZSIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjM5NjMyMDIsImV4cCI6MTY2NDA0OTYwMn0.zY5B8ICoh-2KdOjmpTFbCfllYpWR_OxPCeFt2kh4NQE

### 7) Remover like do post
DELETE http://localhost:3003/posts/like/92bc1f42-ce2c-4329-8420-72a368034320
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MDM5Mzk2MSwiZXhwIjoxNjYwNDgwMzYxfQ.FwOtXHKx1XXFnMot-CJstZPCzEORAtPrwd3iz8QAg5A
