# @name signup

POST http://localhost:3003/signup
Content-Type: application/json

{
   "name": "Jariane", 
   "email": "jari@email.com" ,
   "password": "123456"
}

###
POST http://localhost:3003/login
Content-Type: application/json

{
   "email":"balsemao@email.com",
   "password":"123456" 
}

###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU4NzQyZDFlLWQ1ZDEtNDdjMC05MGJlLWVmMmMxMTM2NjU1OCIsImlhdCI6MTY2MzM3MzQ4OSwiZXhwIjoxNjYzNDU5ODg5fQ.LYjCdfpMbOczF2fjNKMvfB8RKMAruGK0gzRGuA5EEIU


###
GET http://localhost:3003/user/profile
Authorization: {{token}}

###

@id = a68cfd9e-bb8a-48e2-b4bf-fa218d0cc124

###
GET http://localhost:3003/user/a68cfd9e-bb8a-48e2-b4bf-fa218d0cc124
Authorization: {{token}}

###
POST http://localhost:3003/recipie
Content-Type: application/json
Authorization: {{token}}

{
   "title": "Carreteiro",
	"description": "Misture arroz, carne, extrato de tomate e reze pra ficar bom!!!"
}

###
GET http://localhost:3003/recipie/74b9a893-ad2c-4a41-85a3-97e3415e67ca
Authorization: {{token}}
